/******************************************************************************
 *
 * Module: UltraSonic
 *
 * File Name: UltraSonic.h
 *
 * Description: Header file for the UltraSonic driver
 *
 * Author: Ahmed Hassabou
 *
 *******************************************************************************/

#ifndef UltraSonic_H_
#define UltraSonic_H_

#include "std_types.h"

/*
 *  Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

extern uint8 g_edgeCount;

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

void Ultrasonic_init(void);
/*
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);
/*
 * Send the trigger pulse by using Ultrasonic_Trigger function
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);
/*
 * This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void);

#endif
